language: python

python:
  - 3.6

cache: pip

install:
  - pip install -r lint_requirements.txt
  - pip install -r requirements.txt

jobs:
  include:
    - stage: lint
      script:
        - sh ./lint.sh

    - stage: run
      script:
        - python -m generator -i ./resources/sample_config.yaml -o nemesis.bin
